{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "my-pro-template.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-pro-template.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "my-pro-template.selectorLabels" . | nindent 6 }}

  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}

  ingress:
    {{- if .Values.networkPolicy.ingress }}
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- range .from }}
        {{- if .podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector.matchLabels | nindent 14 }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector.matchLabels | nindent 14 }}
        {{- end }}
        {{- if .ipBlock }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr }}
        {{- end }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- else }}
    []  # Deny all ingress if not defined
    {{- end }}

  egress:
    {{- if .Values.networkPolicy.egress }}
    {{- range .Values.networkPolicy.egress }}
    - to:
        {{- range .to }}
        {{- if .podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector.matchLabels | nindent 14 }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector.matchLabels | nindent 14 }}
        {{- end }}
        {{- if .ipBlock }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr }}
        {{- end }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
    {{- else }}
    []  # Deny all egress if not defined
    {{- end }}
{{- end }}