{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "my-app-template.fullname" . }}-network-policy
spec:
  podSelector: {}
  ingress: {{ toYaml .Values.networkPolicy.ingress | nindent 2 }}
{{- end }}