{{- if .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "my-app-template.fullname" . }}-peerauth
spec:
  mtls:
    mode: {{ .Values.peerAuthentication.mtls.mode }}
{{- end }}