networkPolicy:
  enabled: true  # Enable or disable the NetworkPolicy

  policyTypes:
    - Ingress
    - Egress  # You can choose to only have one if desired

  # List of Ingress rules (can be empty list [])
  ingress:
    # Example 1
    - from:
        - podSelector:
            matchLabels:
              app: internal-api-gateway
      ports:
        - protocol: TCP
          port: 8080

    # Example 2
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9100

  # List of Egress rules (can be empty list [])
  egress:
    # Example 1
    - to:
        - namespaceSelector:
            matchLabels:
              name: database
      ports:
        - protocol: TCP
          port: 5432

    # Example 2
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0  # Open internet (use with caution)
      ports:
        - protocol: TCP
          port: 443
