{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "my-pro-template.fullname" . }}-vs
spec:
  hosts: {{ toYaml .Values.virtualService.hosts | nindent 2 }}
  gateways: {{ toYaml .Values.virtualService.gateways | nindent 2 }}
  http: {{ toYaml .Values.virtualService.http | nindent 2 }}
{{- end }}